### ISSUE TITLE
Port code from old repo

### ISSUE THREAD

**Issue by tipsy** [javalin/javalin-graphql#2]
I made this template that could be used as a starting point: https://github.com/javalin/javalin-repo-template

**Comment by tipsy** [comment]
<img width="685" alt="Screen Shot 2022-06-16 at 22 33 12" src="https://user-images.githubusercontent.com/1521451/174158790-853296c9-33f0-4692-ba1a-f1cccc157aea.png">

**Comment by 7agustibm** [comment]
Hi @tipsy! 

I have migrated the code, but I have problems with the WebSocket. It gives me this error:

```
[main] INFO io.javalin.Javalin - 
       __                      __ _            __ __
      / /____ _ _   __ ____ _ / /(_)____      / // /
 __  / // __ `/| | / // __ `// // // __ \    / // /_
/ /_/ // /_/ / | |/ // /_/ // // // / / /   /__  __/
\____/ \__,_/  |___/ \__,_//_//_//_/ /_/      /_/

          https://javalin.io/documentation

[main] INFO org.eclipse.jetty.util.log - Logging initialized @875ms to org.eclipse.jetty.util.log.Slf4jLog
[main] INFO io.javalin.Javalin - Starting Javalin ...
[main] INFO io.javalin.Javalin - You are running Javalin 4.6.3 (released June 16, 2022).
[main] INFO io.javalin.Javalin - No port specified, starting on port 8080. Call start(port) to change ports.
[main] INFO io.javalin.Javalin - Listening on http://localhost:8080/
[main] INFO io.javalin.Javalin - Javalin started in 112ms \o/
[JettyServerThreadPool-36] WARN io.javalin.Javalin - Uncaught exception in WebSocket handler
java.lang.IllegalStateException: GraphQL Error WebSocket -> Cannot call method public final void io.javalin.websocket.WsConnection#onMessage(org.eclipse.jetty.websocket.api.Session, java.lang.String) with args: [org.eclipse.jetty.websocket.common.WebSocketSession, java.lang.String]
	at io.javalin.plugin.graphql.GraphQLPlugin.apply$lambda-4$lambda-3(GraphQLPlugin.kt:39)
	at io.javalin.websocket.WsConnection$onError$1.invoke(WsConnection.kt:62)
	at io.javalin.websocket.WsConnection$onError$1.invoke(WsConnection.kt:62)
	at io.javalin.websocket.WsConnection.tryBeforeAndEndpointHandlers(WsConnection.kt:71)
	at io.javalin.websocket.WsConnection.onError(WsConnection.kt:62)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.jetty.websocket.common.events.annotated.CallableMethod.call(CallableMethod.java:70)
	at org.eclipse.jetty.websocket.common.events.annotated.OptionalSessionCallableMethod.call(OptionalSessionCallableMethod.java:68)
	at org.eclipse.jetty.websocket.common.events.JettyAnnotatedEventDriver.onError(JettyAnnotatedEventDriver.java:192)
	at org.eclipse.jetty.websocket.common.WebSocketSession.callApplicationOnError(WebSocketSession.java:416)
	at org.eclipse.jetty.websocket.common.io.AbstractWebSocketConnection.close(AbstractWebSocketConnection.java:209)
	at org.eclipse.jetty.websocket.common.WebSocketSession.close(WebSocketSession.java:130)
	at org.eclipse.jetty.websocket.common.events.AbstractEventDriver.incomingFrame(AbstractEventDriver.java:173)
	at org.eclipse.jetty.websocket.common.WebSocketSession.incomingFrame(WebSocketSession.java:326)
	at org.eclipse.jetty.websocket.common.extensions.ExtensionStack.incomingFrame(ExtensionStack.java:202)
	at org.eclipse.jetty.websocket.common.Parser.notifyFrame(Parser.java:225)
	at org.eclipse.jetty.websocket.common.Parser.parseSingleFrame(Parser.java:259)
	at org.eclipse.jetty.websocket.common.io.AbstractWebSocketConnection.onFillable(AbstractWebSocketConnection.java:459)
	at org.eclipse.jetty.websocket.common.io.AbstractWebSocketConnection.onFillable(AbstractWebSocketConnection.java:440)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
	at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:338)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:315)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:173)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produce(EatWhatYouKill.java:137)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:883)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1034)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

Have you ever seen this error?

**Comment by tipsy** [comment]
I haven't seen it before. Can you try depending on the 5.0 snapshot instead of 4.x? You can see how that's done in the javalin-rendering repo. You need to add reposilite to the pom.

**Comment by 7agustibm** [comment]
It's working. Already migrated, just need to publish it in Maven.

**Comment by tipsy** [comment]
Great @7agustibm, thank you very much !

**Comment by tipsy** [comment]
We'll figure out how to do the release once 5.0 is getting close to ready :)
